openapi: 3.0.0
info:
  title: Competition Management API
  version: 1.0.0
  description: An API to manage football competitions.

servers:
  - url: https://api.football-competition.com/v1
    description: Production server

paths:
  /competitions:
    get:
      summary: Get a list of competitions
      description: Retrieve a list of all football competitions.
      responses:
        '200':
          description: A list of competitions.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Competition'

    post:
      summary: Create a new competition
      description: Create a new football competition.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Competition'
      responses:
        '201':
          description: Competition created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Competition'

components:
  schemas:
    Competition:
      type: object
      properties:
        name:
          type: string
          example: LIGA
        location:
          type: string
          example: SPAIN
