openapi: 3.0.0
info:
  title: Team-Players Management API
  version: 1.0.0
  description: An API to manage the association of players with teams.

servers:
  - url: https://api.football-competition.com/v1
    description: Production server

paths:
  /teams/{teamId}/players:
    get:
      summary: Get a list of players for a team
      description: Retrieve a list of all players for a specific team, with optional filtering by player name.
      parameters:
        - name: teamId
          in: path
          required: true
          description: The ID of the team.
          schema:
            type: string
            example: 12345
        - name: playerName
          in: query
          description: Filter players by name.
          schema:
            type: string
            example: Jude Bellingham
      responses:
        '200':
          description: A list of players.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'

    post:
      summary: Add players to a team
      description: Associate a list of players with a specific team.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Player'
      responses:
        '200':
          description: Players added successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
