openapi: 3.0.0
info:
  title: Team Management API
  version: 1.0.0
  description: An API to manage football teams.

servers:
  - url: https://api.football-competition.com/v1
    description: Production server

paths:
  /teams:
    get:
      summary: Get a list of teams
      description: Retrieve a list of all football teams, with optional filtering by team name.
      parameters:
        - name: teamName
          in: query
          description: Filter teams by name.
          schema:
            type: string
            example: Real Madrid
      responses:
        '200':
          description: A list of teams.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'

    post:
      summary: Create a new team
      description: Create a new football team.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Team'
      responses:
        '201':
          description: Team created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'

components:
  schemas:
    Team:
      type: object
      properties:
        name:
          type: string
          example: Real Madrid
        slogan:
          type: string
          example: "Hala Madrid"
